linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild
  - nx

ignoredBuiltDependencies:
  - "@scarf/scarf"

packages:
  - userdb/*
  - libs/*

allowedDeprecatedVersions:
  glob: "*"
  inflight: "*"

